name: Postgres Service Example

on:
  push:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified continer rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  python:3.7.4-slim
      env:
        PIPENV_VENV_IN_PROJECT: '1'

    #    services:
    #      postgres:
    #        image: postgres:10.8
    #        env:
    #          POSTGRES_USER: postgres
    #          POSTGRES_PASSWORD: postgres
    #          POSTGRES_DB: postgres
    #        ports:
    #          - 5432:5432
    #        # needed because the postgres container does not provide a healthcheck
    #        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Show OS info
        - run: uname -a
      - name: Show python version
        - run: which -a python
        - run: python --version
#      - run: which -a pipenv
#      - run: pipenv --version
