name: GitHub Actions Sample

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified continer rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  python:3.7.4-slim
      env:
        PIPENV_VENV_IN_PROJECT: '1'

    services:
      dynamodb:
        image: amazon/dynamodb-local
    #      postgres:
    #        image: postgres:10.8
    #        env:
    #          POSTGRES_USER: postgres
    #          POSTGRES_PASSWORD: postgres
    #          POSTGRES_DB: postgres
    #        ports:
    #          - 5432:5432
    #        # needed because the postgres container does not provide a healthcheck
    #        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install pipenv==2018.11.26
      - name: Show versions
        run: |
          which -a python
          python --version
          which -a pip
          pip --version
          which -a pipenv
          pipenv --version
